Closes issue #11 and #12
lobstahbots/2024-Robot-Code pull request #20
Opened 2024-01-21 04:51 UTC by ChiliRhino417

Creates climber subsystem with Advantage kit and logging stuff as well as move climber and stop climber commands

2024-01-21 05:42 UTC, kchenturtles requested changes
Can you use the @param notation for your javadocs? Just for consistency. Also line 11 of javadocs for MoveClimberCommand should say "ClimberCommand" not "climberComand". StopClimberCommand should require the climber subsystem too. Javadocs for the Climber subsystem aren't correct anymore after implementing advantagekit.

2024-01-23 21:36 UTC, citrus-melon approved these changes

2024-01-23 21:36 UTC, citrus-melon commented on src/main/java/frc/robot/subsystems/Climber.java
> +   * @param io A ClimberIO representing the hardware layer. I
I?

2024-01-24 04:20 UTC, kchenturtles approved these changes

2024-01-24 04:21 UTC, merged