Add photonvision subsystem
lobstahbots/2024-Robot-Code pull request #40
Opened 2024-02-06 21:28 UTC by pigrammer3

Closes #1

2024-02-07 16:07 UTC, kchenturtles requested changes

2024-02-07 16:07 UTC, kchenturtles commented on src/main/java/frc/robot/subsystems/PhotonVision.java
> +    }
you appear to be missing void periodic(){} and Logger.processInputs()

2024-02-11 19:47 UTC, kchenturtles approved these changes

2024-02-12 00:41 UTC, citrus-melon approved these changes

2024-02-12 00:41 UTC, citrus-melon commented on src/main/java/frc/robot/subsystems/PhotonVision.java
> +        if (sumConfidence != 0) averagePose = new Pose2d(sumX, sumY, sumRotation).div(sumConfidence);
I wonder if it's possible to operate on Pose2ds for the addition and multiplication as well

2024-02-12 00:41 UTC, citrus-melon commented on src/main/java/frc/robot/subsystems/PhotonVision.java
> +        return inputs.estimatedRearPoseTimestamp > inputs.estimatedFrontPoseTimestamp ? inputs.estimatedRearPoseTimestamp : inputs.estimatedFrontPoseTimestamp;
Math.max() ?

2024-02-12 02:17 UTC, merged