Add pathplanner autos
lobstahbots/2024-Robot-Code pull request #48
Opened 2024-02-13 18:26 UTC by pigrammer3

Closes #15

2024-02-13 19:07 UTC, citrus-melon commented
Is going to the pickup angle taken care of by the arm default command?

2024-02-15 08:32 UTC, kchenturtles requested changes

2024-02-15 08:32 UTC, kchenturtles commented on src/main/java/frc/robot/RobotContainer.java
> +
Swap the order here. You want to register the named commands before you reference them in SmartDashSetup()

2024-02-15 08:32 UTC, kchenturtles commented on src/main/java/frc/robot/RobotContainer.java
> +  protected Command getOneNoteAuto() {
Better to move these to TrajectoryFactory (now AutoFactory).

2024-02-15 08:32 UTC, kchenturtles commented on src/main/java/frc/robot/RobotContainer.java
> +    */
ShooterConstants.lowerShooterSpeed and ShooterConstants.upperShooterSpeed don't appear to exist.

2024-02-15 08:32 UTC, kchenturtles commented on src/main/java/frc/robot/Constants.java
> +    public static final Pose2d FIRST_NOTE_SHOOTING_POSITION = new Pose2d(0, 0, Rotation2d.fromRotations(0));
Try to find an actual shooting position for this. I suspect it might just be a little bit in front of the first note pickup pose.

2024-02-15 08:32 UTC, kchenturtles commented on src/main/java/frc/robot/Constants.java
> +    public static final Rotation2d NOTE_2_SHOOTING_ANGLE = Rotation2d.fromDegrees(0);
Make up some numbers for this -- it's helpful for pivot simulation

2024-02-15 08:32 UTC, kchenturtles commented on src/main/java/frc/robot/RobotContainer.java
> +    NamedCommands.registerCommand("note2pivot", new RotatePivotCommand(pivot, AutoConstants.NOTE_2_SHOOTING_ANGLE.getRadians()).until(() -> pivot.getPosition().minus(AutoConstants.NOTE_2_SHOOTING_ANG
Perhaps use MathUtil.applyDeadband()? Additionally, please make a constant for the angle deadband for the arm.

2024-02-19 05:38 UTC, kchenturtles approved these changes

2024-02-19 17:29 UTC, citrus-melon commented on src/main/java/frc/robot/AutoFactory.java
> +            .andThen(new SpinShooterCommand(shooter, ShooterConstants.SHOOTER_SPEED, ShooterConstants.SHOOTER_SPEED));
I get the feeling that this command will never end (but I might be wrong)

2024-02-19 17:29 UTC, citrus-melon commented on src/main/deploy/pathplanner/autos/2 Note Auto.auto
> +        },
We should intake before moving the pivot to the note 1 shooting angle

2024-02-19 17:29 UTC, citrus-melon commented on src/main/java/frc/robot/AutoFactory.java
> +    }
Why is this not also a PathPlanner auto?

2024-02-24 15:24 UTC, citrus-melon approved these changes

2024-02-24 15:24 UTC, citrus-melon commented on src/main/java/frc/robot/Constants.java
> +    public static final double SHOOT_TIME = 2; // in seconds
Might make more sense in AutoConstants

2024-02-24 15:29 UTC, citrus-melon commented
Suggested edit:
```diff
diff --git a/src/main/java/frc/robot/RobotContainer.java b/src/main/java/frc/robot/RobotContainer.java
index 29954b0..a114933 100644
--- a/src/main/java/frc/robot/RobotContainer.java
+++ b/src/main/java/frc/robot/RobotContainer.java
@@ -124,11 +124,11 @@ public class RobotContainer {
       }, new PhotonVision(new PhotonVisionReal()), frontLeft, frontRight, backLeft, backRight, false);
       pivot = new Pivot(new PivotSim());
     }
+    
+    this.autoFactory = new AutoFactory(driveBase, shooter, intake, pivot, autoChooser::getResponses);
 
     registerNamedCommands();
 
-    this.autoFactory = new AutoFactory(driveBase, shooter, intake, pivot, autoChooser::getResponses);
-
     setTeleopDefaultCommands();
     
     smartDashSetup();

```

2024-02-24 15:32 UTC, citrus-melon requested changes

2024-02-24 15:32 UTC, citrus-melon commented on src/main/java/frc/robot/RobotContainer.java
>      setTeleopDefaultCommands();
```suggestion

    this.autoFactory = new AutoFactory(driveBase, shooter, intake, pivot, autoChooser::getResponses);

    registerNamedCommands();

    setTeleopDefaultCommands();
```

2024-02-26 22:06 UTC, citrus-melon approved these changes

2024-02-26 22:13 UTC, merged