Note Detection
lobstahbots/2024-Robot-Code pull request #98
Opened 2024-06-17 06:26 UTC by pigrammer3

Closes #44

2024-06-19 19:18 UTC, ChiliRhino417 approved these changes

2024-06-21 05:45 UTC, kchenturtles requested changes

2024-06-21 05:45 UTC, kchenturtles commented on src/main/java/frc/robot/AutoFactory.java
> +                .andThen(new IntakeNoteCommand(indexer, intake).deadlineWith(getPathFindToPoseCommand(selectedNote)));
I'd be careful about ending it exactly when you drive to the note? Might be a good idea to drive a bit "over" the note and keep intaking so you know you picked it up

2024-06-24 17:53 UTC, kchenturtles approved these changes

2024-06-24 17:53 UTC, merged